apiVersion: v1
kind: Namespace
metadata:
  name: zabbix
  labels:
    name: zabbix
---
apiVersion: v1
kind: Service
metadata:
  name: zabbix-web
  labels:
    app: zabbix
  namespace: zabbix
spec:
  ports:
    - port: 80
      targetPort: 80
      name: web-http
  selector:
    name: zabbix-web
  externalIPs:
    - 10.1.17.99
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-server
  labels:
    app: zabbix
    tier: db
  namespace: zabbix
spec:
  ports:
    - port: 5432
      targetPort: 5432
      name: postgres-server
  selector:
    name: postgres-server
---
apiVersion: v1
kind: Service
metadata:
  name: zabbix-server
  labels:
    app: zabbix
  namespace: zabbix
spec:
  ports:
    - port: 10051
      targetPort: 10051
      name: zabbix-trapper
    - port: 162
      targetPort: 162
      protocol: UDP
      name: snmp-trap
  selector:
    name: zabbix-server
  externalIPs:
    - 10.1.17.98
---
apiVersion: v1
kind: Service
metadata:
  name: zabbix-agent
  labels:
    app: zabbix
  namespace: zabbix
spec:
  ports:
    - port: 10050
      targetPort: 10050
      name: zabbix-agent
  selector:
    name: zabbix-agent
---
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: zabbix-web
  labels:
    app: zabbix
    tier: zabbix-web
  namespace: zabbix
spec:
  replicas: 2
  selector:
    matchLabels:
      app: zabbix
      tier: zabbix-web
  template:
    metadata:
      labels:
        name: zabbix-web
        app: zabbix
        tier: zabbix-web
    spec:
      containers:
        - name: zabbix-web
          image: zabbix/zabbix-web-nginx-pgsql:alpine-4.4-latest
          ports:
            - containerPort: 80
              name: web-http
          resources:
            limits:
              cpu: 200m
              memory: 400Mi
            requests:
              cpu: 200m
              memory: 400Mi
          livenessProbe:
            httpGet:
              path: /
              port: web-http
              scheme: HTTP
            initialDelaySeconds: 15
            timeoutSeconds: 2
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 5
          readinessProbe:
            httpGet:
              path: /
              port: web-http
              scheme: HTTP
            initialDelaySeconds: 15
            timeoutSeconds: 2
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 5
          env:
            - name: ZBX_SERVER_NAME
              value: "Zabbix kubernetes"
            - name: PHP_TZ
              value: "Asia/Tokyo"
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: db-zbx-user
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: db-zbx-pass
---
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: postgres-server
  labels:
    app: zabbix
    tier: postgres-server
  namespace: zabbix
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zabbix
      tier: postgres-server
  template:
    metadata:
      labels:
        name: postgres-server
        app: zabbix
        tier: postgres-server
    spec:
      volumes:
        - name: zabbix-pgsql-data
          persistentVolumeClaim:
            claimName: zabbix-pgsql-data-claim
      containers:
        - name: zabbix-db
          image: postgres:latest
          ports:
            - containerPort: 5432
              name: pgsql
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: db-zbx-user
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: db-zbx-pass
          volumeMounts:
            - mountPath: "/var/lib/postgresql/data"
              name: zabbix-pgsql-data
              readOnly: false
---
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: zabbix-server
  labels:
    app: zabbix
    tier: server
  namespace: zabbix
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zabbix
      tier: server
  template:
    metadata:
      labels:
        name: zabbix-server
        app: zabbix
        tier: server
    spec:
      containers:
        - name: zabbix-server
          image: zabbix/zabbix-server-pgsql:alpine-4.4-latest
          ports:
            - containerPort: 10051
              protocol: TCP
              name: zabbix-trapper
          readinessProbe:
            tcpSocket:
              port: zabbix-trapper
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            tcpSocket:
              port: zabbix-trapper
            initialDelaySeconds: 15
            periodSeconds: 20
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: db-zbx-user
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: db-zbx-pass
            - name: ZBX_ENABLE_SNMP_TRAPS
              value: "true"
          volumeMounts:
            - name: zabbix-snmptrap-storage
              mountPath: /var/lib/zabbix/snmptraps/
              readOnly: true
        - name: zabbix-snmptraps
          image: zabbix/zabbix-snmptraps:alpine-4.4-latest
          ports:
            - containerPort: 162
              protocol: UDP
              name: snmp-trap
          volumeMounts:
            - name: zabbix-snmptrap-storage
              mountPath: /var/lib/zabbix/snmptraps/
              readOnly: false
      volumes:
        - name: zabbix-snmptrap-storage
          persistentVolumeClaim:
            claimName: zabbix-snmptrap-data-claim
---
apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: zabbix-agent
  labels:
    app: zabbix
    tier: agent
  namespace: zabbix
spec:
  updateStrategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
  template:
    metadata:
      labels:
        name: zabbix-agent
        app: zabbix
    spec:
      containers:
        - name: zabbix-agent
          image: zabbix/zabbix-agent:alpine-4.4-latest
          resources:
            limits:
              cpu: 100m
              memory: 54Mi
            requests:
              cpu: 100m
              memory: 54Mi
          ports:
            - containerPort: 10050
              name: zabbix-agent
          env:
            - name: ZBX_SERVER_HOST
              value: "zabbix-server"
          securityContext:
            privileged: true
---
apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: zabbix-web
  namespace: zabbix
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: ReplicaSet
    name: zabbix-web
  minReplicas: 1
  maxReplicas: 5
  metrics:
    - type: Resource
      resource:
        name: cpu
        targetAverageUtilization: 70
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: zabbix-pgsql-data-claim
  namespace: zabbix
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: sugi-mapr-mdf-dynamic-sc
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: zabbix-snmptrap-data-claim
  namespace: zabbix
spec:
  accessModes:
    - ReadOnlyMany
  resources:
    requests:
      storage: 10Gi
  storageClassName: sugi-mapr-mdf-dynamic-sc
---
apiVersion: v1
kind: List
metadata:
  namespace: zabbix
items:
  - apiVersion: v1
    kind: Secret
    type: Opaque
    metadata:
      name: db-secret
      namespace: zabbix
    data:
      db-zbx-user: "emFiYml4"
      db-zbx-pass: "emJ4X3Bhc3N3b3Jk"
